# Learn more about configuring your Shopify app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Greywater Directory"
client_id = "e8f6347abf7facf2e1ab850fbc38bf00"
application_url = "https://greywater-directory-shopify-m0p6e2v2q-swilhoits-projects.vercel.app"
embedded = false

[access_scopes]
# No specific scopes needed for App Proxy functionality
scopes = ""

[auth]
redirect_urls = [
  "https://greywater-directory-shopify-m0p6e2v2q-swilhoits-projects.vercel.app/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "https://your-dev-store.myshopify.com"
include_config_on_deploy = true

[[app_proxy]]
url = "https://greywater-directory-shopify-m0p6e2v2q-swilhoits-projects.vercel.app"
subpath = "greywater-directory"
prefix = "apps"