# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9ce5394ae224a6645fc5fa6dfc0dadeb"
name = "Greywater Directory"
application_url = "https://greywater-directory-shopify-exfe5id4u-swilhoits-projects.vercel.app"
embedded = false
handle = "greywater-directory-1"

[access_scopes]
# No specific scopes needed for App Proxy functionality
scopes = ""

[auth]
redirect_urls = [
  "https://greywater-directory-shopify-exfe5id4u-swilhoits-projects.vercel.app/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "waterwisegroup.myshopify.com"
include_config_on_deploy = true

[app_proxy]
url = "https://greywater-directory-shopify-exfe5id4u-swilhoits-projects.vercel.app"
subpath = "greywater-directory"
prefix = "tools"
